# Generated by Django 4.2.21 on 2025-05-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_case_created_by_case_location_alter_case_reporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='created_by',
        ),
    ]
